### PR TITLE
Update file1.sh

### PR DESCRIPTION
**Pull request by davidshoda11**
added line 2 edit, sending pull request to merge into master branch.

### CODE REVIEW

**Comment by davidshoda3** [comment]
davidshoda3 created repository 1, is reviewing changes and sending notification comment to davidshoda11 that davidshoda3 is reviewing changes

**Comment by davidshoda3** [comment]
davidshoda3 sends a comment to davidshoda11 about some of the changes davidshoda11 made

**Comment by davidshoda11** [comment]
davidshoda11 replies to davidshoda3 about the comment davidshoda3 sent to
davidshoda11

**Comment by davidshoda11** [comment]
davidshoda11 replies again via email to davidshoda3 about the comment
davidshoda3 sent to davidshoda11

**Comment by davidshoda9** [comment]
davidshoda9 also makes a comment about the change davidshoda11 is sending a pull request for, davidshoda9 can only leave comments.

**Comment by davidshoda3** [comment]
davidshoda3 repository creator sends okay comment before closing pull request

**Comment by davidshoda3** [comment]
davidshoda3 sends a comment after closing pull request

**Comment by davidshoda9** [comment]
davidshoda9 responds to davidshoda3 after pull request granted and changes merged.

**Comment by davidshoda11** [comment]
davidshoda11 responds to davidshoda9 and davidshoda3 although didn't send any changes and didn't grant committing changes

**Pull request merged**
